### ISSUE TITLE
Morristown, NJ - Letter to Mayor Dougherty and Town Council

### ISSUE THREAD

**Issue by abagree** [defund12/defund12.org#1686] opened 2020-06-21 22:40 UTC
To: mayor@townofmorristown.org, s-armington@townofmorristown.org, t-foster@townofmorristown.org, t-cotten@townofmorristown.org, r-iannaccone@townofmorristown.org, s-mayer@townofmorristown.org, d-silva@townofmorristown.org, m-elms@townofmorristown.org, m-corcoran@townofmorristown.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!)🔗
Dear Mayor Dougherty, Council Members, and Mr. Corcoran:

My name is [YOUR NAME HERE], and I am a resident of Morristown. I live on  [YOUR ADDRESS/STREET]. In light of the urgent Movement for Black Lives happening across our nation and a unified call for justice reform, I am writing to urge you to advocate for a meaningful reallocation of the City's expenditures away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs. 

Accordingly, it has come to my attention that the adoption of the 2020 SID Budget will be held on June 23. At $7,285,252.04 total, an increase from 2019, the City’s amended 2020 budget for policing dwarfs its other appropriations. For example, the allocation for the Public Health department does not even reach $200,000. This is egregious, particularly in light of the global pandemic. The policing budget is more than 35x the entire budget for Public Health. New Jersey has been one of the hardest hit states in the country and while we open up more and more and expect people to come to Morristown for the bars, food, trails, etc. how can we justify this egregious disparity in funding?

I urge you to advocate for a complete overhaul of the City’s budget that directs significant funding away from policing. All over the country, American citizens are calling for budgets that truly represent the people’s needs. In a global pandemic, it is all the more critical to invest funds in areas like health, youth services, and other social programs. Mr. Corcoran outlined that the police responded to approximately 45,000 calls. There is no reason that armed police officers are needed for the vast majority of these calls. These can be done by other trained professionals. There are models for this being developed throughout the country as we speak. I urge you to revise the FY 2020 budget to reflect the demands of Morristown's residents - ideally with participation of those residents in the budget creation - and show that Morristown is committed to a vision of true public safety, one that reduces and eliminates harm for everyone.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by mahrer** [comment] 2020-06-22 04:20
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by aurendisson** [comment] 2020-07-01 01:59
Editing notes: I made some simple updates, mostly around capitalization (no biggie). I did have to update the first line about budget because it mentioned June 23, which has passed. If you have any updates to this, please comment below, and we'll work on incorporating the new info. 
Numbers confirmed here (page 47...it's not searchable): https://www.townofmorristown.org/vertical/sites/%7B0813EA2E-B627-4F82-BBB0-DDEE646947B5%7D/uploads/Morristown_adopted_2020_budget.pdf 

To: mayor@townofmorristown.org, s-armington@townofmorristown.org, t-foster@townofmorristown.org, t-cotten@townofmorristown.org, r-iannaccone@townofmorristown.org, s-mayer@townofmorristown.org, d-silva@townofmorristown.org, m-elms@townofmorristown.org, m-corcoran@townofmorristown.org

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information! And consider adding a couple of sentences in your own words to avoid filters and get your message read.)

Dear Mayor Dougherty, Council Members, and Mr. Corcoran:

My name is [YOUR NAME HERE], and I am a resident of Morristown. In light of the urgent movement for Black lives happening across our nation and a unified call for justice reform, I am writing to urge you to advocate for a meaningful reallocation of the city's expenditures away from policing and towards social programs and resources that support housing, jobs, education, health care, child care, and other critical community needs.

Accordingly, it has come to my attention that the 2020 budget allocated $7,285,252.04 to the police, an increase from 2019, outshining the city's other appropriations. For example, the allocation for the public health department does not even reach $200,000. This is egregious, particularly in light of the global pandemic. The policing budget is more than 35 times the entire budget for public health. New Jersey has been one of the hardest-hit states in the country, and while we open up more and more and expect people to come to Morristown for the bars, food, trails, etc., how can we justify this egregious disparity in funding?

I urge you to advocate for a complete overhaul of the city’s budget that directs significant funding away from policing. All over the country, American citizens are calling for budgets that truly represent the people’s needs. In a global pandemic, it is all the more critical to invest funds in areas like health, youth services, and other social programs. Mr. Corcoran outlined that the police responded to approximately 45,000 calls. There is no reason that armed police officers are needed for the vast majority of these calls. These can be done by other trained professionals. There are models for this being developed throughout the country as we speak. 

I urge you to revise the FY 2020 budget to reflect the demands of Morristown's residents--ideally with the participation of those residents in the budget creation--and show that Morristown is committed to a vision of true public safety and eliminates harm for everyone.

Thank you,
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by root2point0** [comment] 2020-07-01 18:29
on it

**Closed** 2020-07-03 04:57 UTC
Labels: ready-for-pr
