### ISSUE TITLE
Please Add Los Altos, CA; Los Altos Hills, CA; Mountain View, CA; and Santa Clara, CA!

### ISSUE THREAD

**Issue by afishley** [defund12/defund12.org#449] opened 2020-06-06 18:11 UTC
LOS ALTOS, CA

Subject: Los Altos Resident for Defunding the LAPD
emails:
council@losaltosca.gov
jpepper@losaltosca.gov
jbruins@losaltosca.gov
aenander@losaltosca.gov
nfligor@losaltosca.gov
lleeeng@losaltosca.gov

cjordan@losaltosca.gov

To Mayor Pepper and Los Altos City Council Members,

My name is [YOUR NAME], and I am a resident of Los Altos. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this city allocates its resources.

The fact that the Los Altos Police Department encompasses 29.87% percent of the city’s operating budget, while none of it is allocated to affordable housing, nonprofits, and community organizations, is shameful and unproductive. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

There is not just a need for police reform, but police defunding and abolition, because the entire structure of the police force is inherently corrupt and ineffective. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate(Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

We demand the immediate freezing of budget increases to the police force, cancelling of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies.

Please do not vote for more SRO’s in schools, militarized police, and officers patrolling our streets. Do not allow the city to increase police funding another 8%. Do not be complicit in the disproportionate targeting and continuous oppression of people of color. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to revise the Los Altos city budget for the next fiscal year, and to fund #CareNotCops. We can be a beacon for other cities to follow if only we have the courage to change.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

MOUNTAIN VIEW, CA

Subject: Mountain View Resident for Defunding the MVPD

Emails:
citycouncil@mountainview.gov
margaret.abe-koga@mountainview.gov
chris.clark@mountainview.gov
alison.hicks@mountainview.gov
ellen.kamei@mountainview.gov
lisa.matichak@mountainview.gov
john.mcalister@mountainview.gov
lucas.ramirez@mountainview.gov

city.mgr@mountainview.gov
kimbra.mccarthy@mountainview.gov

To Mayor Abe-Koga, Mountain View City Council Members, and the Mountain View City Manager,

My name is [YOUR NAME], and I am a resident of Mountain View. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this city allocates its resources.

The fact that the MVPD encompasses over 42 million dollars of the city’s general operating fund is shameful and unproductive. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

There is not just a need for police reform, but police defunding and abolition, because the entire structure of the police force is inherently corrupt and ineffective. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate(Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

We demand the immediate freezing of budget increases to the police force, cancelling of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies.

Please do not vote to increase police funding by 5.1%. Do not be complicit in the disproportionate targeting and continuous oppression of people of color. Propose and vote to expand on Mountain View’s current efforts like the Below Market Rate housing program and funding of nonprofits like the Community Health Awareness Council. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to revise the Mountain View city budget for the next fiscal year, and to fund #CareNotCops. We can be a beacon for other cities to follow if only we have the courage to change.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

LOS ALTOS HILLS, CA
Subject: Los Altos Hills Resident for Defunding the Police Force

Emails:
ktankha@losaltoshills.ca.gov
mwu@losaltoshills.ca.gov
cccorrigan@losaltoshills.ca.gov
rspreen@losaltoshills.ca.gov
gtyson@losaltoshills.ca.gov
ccahill@losaltoshills.ca.gov

To Mayor Wu, the Los Altos Hills City Council Members, and the Los Altos Hills City Manager.

My name is [YOUR NAME], and I am a resident of Los Altos Hills. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this city allocates its resources.

The fact that the police force encompasses 9.9% of the city’s general fund is shameful and unproductive. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

There is not just a need for police reform, but police defunding and abolition, because the entire structure of the police force is inherently corrupt and ineffective. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate(Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

We demand the immediate freezing of budget increases to the police force, cancelling of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies.

Please do not vote to increase police funding by 3.8%. Do not be complicit in the disproportionate targeting of people of color. Propose and vote to expand on its current efforts like funding of nonprofits like the Community Health Awareness Council and the community services grant rather than cutting it by 20%. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to revise the Los Altos Hills city budget for the next fiscal year, and to fund #CareNotCops. We can be a beacon for other cities to follow if only we have the courage to change.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

SANTA CLARA COUNTY, CA

Subject: Santa Clara County Resident for Defunding the Police Force

emails:
lgillmor@santaclaraca.gov
mike.wasserman@bos.sccgov.org
cindy.chavez@bos.sccgov.org
dave.cortese@bos.sccgov.org
supervisor.ellenberg@bos.sccgov.org
supervisor.simitian@bos.sccgov.org

To Mayor Gillmor and the Santa Clara County Board of Supervisors,

My name is [YOUR NAME], and I am a resident of [CITY] in Santa Clara County. This past week, our nation and community have been gripped by protests calling for an end to racism and anti-blackness and a complete overhaul in our approach to criminal justice in America. We are demanding that our voices be heard, and that real change be made to the way this city allocates its resources.

The fact that the police force encompasses over 895 million dollars of the county’s general fund is shameful and unproductive. Research shows that a living wage, access to holistic health services and treatment, educational opportunity, and stable housing are far more successful at reducing crime than police or prisons (Source: Popular Democracy).

There is not just a need for police reform, but police defunding and abolition, because the entire structure of the police force is inherently corrupt and ineffective. The average police recruit spends 58 hours learning how to shoot and only 8 hours learning how to de-escalate(Source: Campaign Zero). They are not trained or equipped to react to the vast majority of crises. Phillip McHarris (doctoral candidate focusing on race), argues that we must work towards a reality in which healthcare workers and emergency response teams handle substance abuse, domestic violence, homelessness, or mental health cases. Policies to “improve the police” are not enough, as there’s no evidence that implicit bias training or community relations initiatives help with reducing the abuses of policing (The Nation). We need to reimagine public safety to prioritize alternatives to conflict rather than defaulting to violence.

We demand the immediate freezing of budget increases to the police force, cancelling of cadet classes, demilitarization of our forces, and reallocation of funds from police to community-led health and safety strategies.

Please do not vote to increase police funding. Do not be complicit in the disproportionate targeting of people of color. Propose and vote to expand on its current efforts in healthcare, affordable housing, and restorative justice. We demand a budget that supports community wellbeing, rather than empowers the police forces that tear them apart.

It is your duty to represent your constituents. I am urging you to revise the Santa Clara County budget for the next fiscal year, and to fund #CareNotCops. We can be a beacon for other cities to follow if only we have the courage to change.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

Thank you for your amazing work!!

**Comment by emilyhuntsman** [comment] 2020-06-06 18:53
duplicate of #434 ?

**Comment by afishley** [comment] 2020-06-06 18:55
yes! sorry i made a blank request instead of an email request the first time so wasn't sure whether I had to redo it

**Closed** 2020-06-07 02:37 UTC
Labels: ready-for-pr
