### ISSUE TITLE
Email Script to Defund Providence Police

### ISSUE THREAD

**Issue by m00ncak3** [defund12/defund12.org#537] opened 2020-06-06 23:21 UTC
These are the email addresses for Governor Raimondo, Mayor Elorza, the City Clerk, and the members of the City Council’s Finance Committee.

The Finance Committee meets at 5:00pm on Monday 6/8 (watch it [here](https://council.providenceri.gov/)) and the budget will be passed by 6/30 - so send your email ASAP!

**TO:**
governor@governor.ri.gov, Mayor@providenceri.gov, sselleck@providenceri.gov, Ward2@providenceri.gov, Ward5@providenceri.gov, Ward7@providenceri.gov, Ward8@providenceri.gov, Ward9@providenceri.gov

**SUBJECT:** 
Defund Providence Police

**MESSAGE:** _(please replace the [x's] with your information)_
Hello,

My name is [name] and I am a resident of Providence. I am writing to demand that Governor Raimondo, Mayor Elorza and the members of the City Council do everything in their power to adopt a budget that redirects all funds from the Police Department and towards community wellbeing, mental health and the needs of its residents. It has become clear that police forces are ineffective at keeping local communities safe, and that they perpetuate the oppression of residents who are people of color, undocumented, mentally ill, disabled, and LGBTQ. While Providence has received a $700,000 grant to formulate a Behavioral Health Response Team, that amount is a mere drop in the bucket of the nearly $90 million budgeted for Police in 2021. The current budget proposal has allocated $961,000 on guns and ammunition, $1,461,620 for 50 new police recruits, not to mention $14.9 million for uniforms and "wearing apparel,” presumably including more of the riot gear that is currently being used to suppress peaceful protests. Imagine how much those dollars could accomplish when used to fund low-income and public housing, education, resources for formerly incarcerated individuals, and public transportation, as Direct Action for Rights and Equality has demanded.

Providence may be a small city, but we have shown that we can make a huge impact on the United States at large. We desperately need to change our financial priorities and let our tax dollars go to communities, not cops.

Thank you for your time,
[name]
[address]
[email address]
[phone number]

**Comment by serifluous** [comment] 2020-06-07 07:47
Duplicate of issue #24

**Closed** 2020-06-08 12:41 UTC
Labels: duplicate
