### ISSUE TITLE
Fayetteville, NC Letter to Mayor

### ISSUE THREAD

**Issue by deindustrialization** [defund12/defund12.org#1467] opened 2020-06-12 14:37 UTC
Mitch.Colvin@ci.fay.nc.us

Dear Mayor Colvin, 

My name is [NAME] and I am a resident of Fayetteville. I urge you and the rest of the city council to amend the proposed budget for 2021 in order to reallocate funding from the police to social services. I would like to redirect money away from the Fayetteville Police Department and into social service programs that will benefit the public health and our communities, especially communities of color. The proposed budget for 2021 proposes that 38% of the city’s operating budget go to policing ($60,550,000), which is almost double the cost of even the second largest allocation of funds, fire & emergency management ($30,260,000). Meanwhile, only 0.8% of the city's operating budget is being proposed for economic and community development ($1,300,000). This means the city of Fayetteville is spending 40x the amount of money police than they are on community development! This is unconscionable. Particularly, in this unprecedented time of the COVID-19 pandemic, with many of our community members facing unemployment and housing/food insecurity, it is vital that we reallocate funds to social and community services that will develop our communities and support our residents. 

However, it is clear that the police cannot protect us from these challenges. In fact, more often than not, when police are dispensed, rather than more qualified medical, psychiatric, and social work professionals, the effect is to bring violence where none previously existed. Moreover, to paraphrase an existing council member, it is not cities with the most police, but the most resources, that are the safest. This means that crime usually happens when someone has been unable to meet their basic needs through other means. So, to really “fight crime,” we don’t need more police officers - we need more jobs, more educational opportunities, more arts programs, more community centers, more mental health resources, as well as more of a say in how our communities function and how they are funded. This will be a long transformational process, but an important first step is reallocating city funding!

Mayor Colvin, can I count on your to commit to an alternative budget that reallocates police funding to improve social services for our community members?

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment] 2020-06-12 17:52
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by brickaney** [comment] 2020-06-19 02:53
@mahrer please mark as duplicate of issue #240 & #1063.

**Comment by mahrer** [comment] 2020-06-19 02:57
@brickaney Those issues were closed because there was no content.

**Comment by brickaney** [comment] 2020-06-19 04:02
@mahrer Ah i see. Ok, Ive reviewed this letter.

Edits made: structural, added reference, minor content edits to adhere to email guidelines.

“TO: Mitch.Colvin@ci.fay.nc.us

Subject: [UNIQUE SUBJECT LINE]

Dear Mayor Colvin,

My name is [NAME] and I am a resident of Fayetteville. I am writing to urge you and the rest of the city council to amend the proposed budget for 2021 in order to reallocate funding from the police to social services. I would like to redirect money away from the Fayetteville Police Department and into social service programs that will benefit the public health and our communities, especially communities of color. 

The proposed budget for 2021 proposes that 30% of the city’s general fund go to policing, meanwhile, only 0.8% of the city's operating budget is being proposed for economic and community development. This means the city of Fayetteville prioritizes police 30X more than community development. This is unconscionable. Particularly, in this unprecedented time of the COVID-19 pandemic, with many of our community members facing unemployment and housing/food insecurity, it is vital that we reallocate funds to social and community services that will develop our communities and support our residents.

Moreover, to paraphrase an existing council member, it is not cities with the most police, but the most resources, that are the safest. This will be a long transformational process, but an important first step is reallocating city funding.

Mayor Colvin, can I count on your to commit to an alternative budget that reallocates police funding to improve social services for our community members?

Thank you,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

[1] https://fayettevillenc.gov/Home/ShowDocument?id=14504

**Comment by todd-m** [comment] 2020-06-19 17:41
on it

**Closed** 2020-06-20 15:07 UTC
Labels: ready-for-pr
