### ISSUE TITLE
Please add Vacaville, CA

### ISSUE THREAD

**Issue by ccaringa** [defund12/defund12.org#1066] opened 2020-06-09 07:40 UTC
To:
Ron.Rowlett@cityofvacaville.com<Ron.Rowlett@cityofvacaville.com>;
raymond.beaty@cityofvacaville.com  raymond.beaty@cityofvacaville.com ;
dilenna.harris@cityofvacaville.com  dilenna.harris@cityofvacaville.com ;
mitch.mashburn@cityofvacaville.com  mitch.mashburn@cityofvacaville.com ;
nolan.sullivan@cityofvacaville.com nolan.sullivan@cityofvacaville.com ;

Subject: [***INSERT UNIQUE SUBJECT LINE***]

Message (Don’t forget to replace the [x]’s with your information!)

Dear Mayor Rowlett and Vacaville City Council,

My name is [YOUR NAME] and I am a resident of Vacaville, CA. With recent events, Americans joined by many other nations been protesting within their hometowns and local cities arm in arm in order to end racism in hopes to create lasting change. Vacaville’s city mission is to balance the citizens’ needs, desires, and resources to achieve the highest possible quality life for the overall community. I urge Mayor Rowlett and the Vacaville City Council to amend the city budget and reallocate funds towards social services in order to better serve its people.

The Vacaville Police department budget is projected to be $42,366,797 for the 2020/2021 fiscal year which is a 7.37% increase from the adjusted 2019/2020 adjusted budget. The police department accounts for the single largest department expenditure for the city budget and makes up 40% of the FY20/21 general budget fund with only 1 proposed mental health clinician and 3 mental health coordinators for a city with a population of 103,336 people. According to the Treatment Advocacy Center, cops disproportionately hurt and kill people with mental illness. In addition, 1 in 4 people killed by the police have a serious mental illness, and 21% of police time is spent responding to or transporting people with mental illness. A program is needed to aid this special population: one consisting of more social workers and mental health professionals who are trained in mental health, nonviolent crisis intervention, and de-escalation techniques which are necessary for helping individuals with mental health needs.

A mental health program has been enforced in Eugene, Oregon for 30 years which consists of a non-police crisis providing crisis counseling, suicide intervention, substance abuse response, conflict resolution and mediation, resource referrals, transportation to services, and aids in the housing crisis. Evidence has shown that this program is cheaper. Oregon crisis workers handle 17% of 911 calls and cost 1% of the police department’s budget. By doing this, police, ambulance, and fire resources are conserved. More cities in California are implementing social work and emergency response teams such as San Mateo, Sacramento, and Los Angeles.

We need to take care of our people, and that requires action on our part in order to make a change. We cannot let our people be failed by our mental health system. We need to create a safe space in which we can provide the necessary services to take care of each other. 

Thank you,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by skullface** [comment] 2020-06-09 15:49
Thanks for following up with us @ccaringa! This is now in the queue for review.

**Comment by brickaney** [comment] 2020-06-12 01:59
I’m reviewing.

**Comment by brickaney** [comment] 2020-06-12 02:27
@skullface : Oops, can you close this issue as it is a duplicate of another request that has been closed (I don’t have permissions to edit labels yet).

@ccaringa Thank you for your submission. Vacaville has already been added by another user. If you’d like to make edits to their submission, submit a new issue.

**Closed** 2020-06-12 20:18 UTC
Labels: content-ready-for-review
