### ISSUE TITLE
Marin County Email Template to District Supervisors, Mayors, and City Council

### ISSUE THREAD

**Issue by erinb0731** [defund12/defund12.org#1146] opened 2020-06-09 20:27 UTC
BOS@marincounty.org, dconnolly@marincounty.org, krice@marincounty.org, ksears@marincounty.org, drodoni@marincounty.org, jarnold@marincounty.org, nkemnitzer@cityofbelvedere.org, jcampbell@cityofbelvedere.org, cmcauliffe@cityofbelvedere.org, bmccaskill@cityofbelvedere.org, mwinter@cityofbelvedere.org, ebeckman@tcmmail.org, dkunhardt@tcmmail.org, fcasissa@tcmmail.org, clee@tcmmail.org, bravasio@tcmmail.org, jreed@townoffairfax.org, shellman@townoffairfax.org, bcoler@townoffairfax.org, backerman@townoffairfax.org, rgoddard@townoffairfax.org, cway@cityoflarkspur.org, kharoff@cityoflarkspur.org, scandell@cityoflarkspur.org, dhillmer@cityoflarkspur.org, gpaulson@cityoflarkspur.org, smcentee@cityofmillvalley.org , jmccauley@cityofmillvalley.org, jwickham@cityofmillvalley.org, ucarmel@cityofmillvalley.org, tossa@cityofmillvalley.org, dathas@novato.org, peklund@novato.org, elucan@novato.org, apeele@novato.org, swernick@novato.org, juliemcmillan@comcast.net, eliz.robbins@gmail.com, elizabethb@brekhus.com, cwkmisc@gmail.com, beachkuhl35@gmail.com, fordgreene@comcast.net, bcolbert@townofsananselmo.org, jwright@townofsananselmo.org, afineman@townofsananselmo.org, sburdo@townofsananselmo.org, gary.phillips@cityofsanrafael.org, maribeth.bushey@cityofsanrafael.org, kate.colin@cityofsanrafael.org, john.gamblin@cityofsanrafael.org, andrew.mccullough@cityofsanrafael.org, sclevelandknowles@sausalito.gov, rwithy@sausalito.gov, jburns@sausalito.gov, jcox@sausalito.gov, treilly@sausalito.gov, afredericks@townoftiburon.org, hollithiertiburontowncouncil@gmail.com, dkulik@townoftiburon.org, jryan@townoftiburon.org, jwelner@townoftiburon.org

-------------------------------

Dear Elected Officials of Marin County,

My name is [INSERT YOUR NAME], and I am a concerned resident of Marin County. I demand that action be taken to support and uplift Black people and other communities of color in our predominantly white county, starting with defunding the police department under your purview. 

We do not need the level of policing that has been financially allocated in Marin County. The Marin County 2020-2021 budget projects a net use of over $50 million in the Marin County Sheriff’s Office, an increase of over $6.6 million compared to the Sheriff Office’s budget from the last fiscal year (Marin County Administrator, “2020/2021 Proposed Budget,” 79). To be clear, this allocation does not include the additional budgets for the 14 local police departments in Marin County (Marin County District Attorney, “Local Law Enforcement Links”). There is absolutely no reason to allocate or invest more money into our county’s police forces, especially in light of ongoing discriminatory policing practices: Marin County is ranked #2 in California for most racial disparity in issues pertaining to crime and justice (Race Counts, “County Rankings”). Despite the fact that Black people make up a mere 3% of Marin County’s population, Black people account for 27% of arrests made countywide, and furthermore, 84% of law enforcement officials in Marin County are white (Marin County Administrator, “2020/2021 Proposed Budget,” 40; see also Race Counts, “Marin”). Anything other than a significant and permanent reduction in the funds allocated to our police departments sends a clear message that the unjust profiling, harassment, and incarceration of Black people in Marin County is considered acceptable.  

On all municipal levels, Marin County and its incorporated cities must work to address systemic racism by, in part, divesting from the police and instead investing in community-based social services and programs. Marin’s population is 83% white, and according to Race Counts, Marin County has the highest racial disparity in California in terms of access to housing, healthcare, economic opportunity, and more (Marin County Administrator, “2020/2021 Proposed Budget,” 40; see also Race Counts, “County Rankings”). Despite our county’s immense wealth and resources, Black people continue to face institutional discrimination: they are priced out of this county due to exorbitant living costs, discriminated against by educational systems, and disproportionately profiled and targeted by local law enforcement (August 9, 2019, New York Times, “Separate Programs for Separate Communities;” see also Race Counts, “Marin”). To that end, I request that you actively work to redirect law enforcement funds into health and human services, community development, and community services; invest in, and partner with, nonprofits and grassroots organizations in your area that uplift communities of color, and encourage government officials to develop better youth programs, mental health services, rehabilitation programs, affordable housing developments, childcare, child support, etc.

I urge you to divest from the police, and invest in Marin County’s Black and non-Black communities of color.

Thank you for your attention to this pressing matter,
[INSERT YOUR NAME]
Resident of Marin County

**Comment by xbytof** [comment] 2020-06-10 22:48
@erinb0731 thanks so much for submitting this for Marin!!

**Comment by brickaney** [comment] 2020-06-12 02:35
@bingbongle This is a duplicate of 4 other issues. Please add duplicate label.

@erinb0731 Thank you for your submission. Marin County has already been added. If you’d like to add on to that submission or make edits please submit a new request.

**Closed** 2020-06-12 20:26 UTC
Labels: content-ready-for-review
