### ISSUE TITLE
Please Add Reno, NV to defund 12!!!

### ISSUE THREAD

**Issue by moregainaudio** [defund12/defund12.org#159] opened 2020-06-05 04:34 UTC
**SUBJECT:** Reno Residents for Defunding RPD

**EMAILS:**

mayor@reno.gov
reesed@reno.gov,
brekhusj@reno.gov, 
duerrn@reno.gov,
delgadoo@reno.gov,
weberb@reno.gov,
jardonn@reno.gov,

**BODY:**

I am a resident of Reno. I am writing to demand that Mayor Hillary Schieve and City Council to do everything in their power to adopt a budget that prioritizes our community well being and redirects funding away from the police in the next budget evaluation period.

We have seen mounting evidence that police departments are racist and ineffective institutions that put citizens at risk of injury and death, yet the police budget accounts for 36% of our general fund. 

I ask that you redirect the majority of the $41.9M allotted for crime prevention toward community programs that provide residents with basic human needs like affordable healthcare and housing. With over 20% of our residents currently unemployed, we need funding to address the needs of people hurting from the effects of COVID 19, people experiencing homelessness, and the marginalized communities in our city.

I also STRONGLY URGE the City Council to enact legislation instituting a community elected Civilian Police Accountability Council with the following powers; ability to review and change disciplinary actions, review all violent interactions, and impose discipline including firing.

Our community is in pain along with the nation. We desperately need to change what we are prioritizing.   

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by teddywilson** [comment] 2020-06-05 12:01
Thank you for sharing - we will take a look!

**Comment by moregainaudio** [comment] 2020-06-06 19:01
Hello!

Please update the Reno,NV email. It has come to our attention that our sitting chief of police has been made ACTING CITY MANAGER, putting him in charge of the proposing the city's budget! this rewrite of the subject and body of the letter reflect that.

**SUBJECT:** Reno Residents For Defunding RPD, and Against Jason Soto as Acting City Manager

**BODY:**

I am a resident of Reno. I am writing to demand that Mayor Hillary Schieve and City Council to do everything in their power to IMMEDIATELY redirect the majority of the $41.9M allotted for crime prevention toward community programs that provide residents with basic human needs like affordable healthcare and housing, as well as youth programming and the arts.

We have seen mounting evidence that police departments are racist and ineffective institutions that put citizens at risk of injury and death, yet the police budget accounts for 36% of our general fund.

Im asking that chief of police Jason Soto IMMEDIATELY BE REMOVED AS ACTING CITY MANAGER. He CAN NOT be allowed to manage our city’s budget when he directly benefits from appropriating as much funding as he can to the police department. This is a conflict of interest that reflects negatively on all members of city council as he was elected unanimously.

I ask that use of militarized weapons such as tear gas, rubber bullets, and flash bangs be BANNED in Reno WITH ABSOLUTELY NO EXCEPTION!

I also STRONGLY URGE the City Council to enact legislation instituting a community elected Civilian Police Accountability Council with the following powers; ability to review and change disciplinary actions, review all violent interactions, and impose discipline including firing. I ask that NO additional funds be allocated for the creation/reformation of this board, its funding should come from the remaining police budget.

Thank you for your time,

[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]

**Comment by teddywilson** [comment] 2020-06-06 20:44
Duplicate of: https://github.com/defund12/defund12.org/pull/166

Should we augment content, create new template, or close this out.

**Comment by moregainaudio** [comment] 2020-06-06 20:48
I'll close this issue and leave #472 open. thank you very much!

**Comment by moregainaudio** [comment] 2020-06-06 21:21
sorry! i didn't fully understand the question. please augment the content of #166 with the new subject and body in my previous comment. i'll close #472 once this underway

**Comment by serifluous** [comment] 2020-06-07 23:52
Closing since this is duplicated in #472

**Closed by serifluous** 2020-06-07 23:52 UTC
Labels: duplicate
