### ISSUE TITLE
San Bruno, CA 

### ISSUE THREAD

**Issue by monarch27** [defund12/defund12.org#1268] opened 2020-06-10 06:11 UTC
To: councilsb@sanbruno.ca.gov

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!)

To Mayor Medina and the San Bruno City Council,

My name is [XXXXXXX] and I am a resident of San Bruno. As the nation grapples with the devastating, brutal deaths of George Floyd and Breonna Taylor (among so many others) and the economic impact of COVID-19, I am writing to express my strong concerns with the San Bruno Police Department budget.

I am astonished to learn that the SBPD received 38.9% of the general fund budget in FY2019-20 and will receive 39.1% in FY2020-21. This is even more astonishing considering the small, small numbers of officers who have graduated from a crisis training program: an estimated 9 in 19-20 and a target 6 in 20-21. I am deeply concerned about the priorities of the SBPD and San Bruno in general.       

The 20-21 goal of expanding services to unhoused persons is certainly a noble one, but I am left wondering why such services are being rendered by police rather than trained counselors or experts in homelessness, substance use, and trauma. Similarly, I am alarmed by the extensive presence of officers in schools and concerned that youth-centered programming seems to be under the purview of the police department rather than the library or Recreation Services—or trained educators and counselors in general.

We must consider how far that 39.1% of the budget would go toward other non-violent, prevention-oriented services that address our livelihoods and humanity such as health services (include mental health services) social services, infrastructure, childcare assistance, homelessness services, libraries, and our parks and recreation services. Overall, we need to reimagine public safety to address root causes of community distress rather than defaulting to punishment, incarceration, and violence.

I call on you to slash the SBPD budget and instead apply these resources towards these stated alternatives. I hope that our city does indeed have enough heart to make bold changes that uplift us all and establish a positive, nurturing foundation for generations to come.

Sincerely,
[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by mahrer** [comment] 2020-06-10 06:27
Thank you for submitting your city to defund12.org! Your request is now in the queue for review and publishing. We’ll reply here if we have any questions.

**Comment by wendywx** [comment] 2020-06-14 16:52
edits in bold:

-------------------------------------------------------------

To: councilsb@sanbruno.ca.gov, **RMedina@sanbruno.ca.gov, MSalazar@sanbruno.ca.gov, LDavis@sanbruno.ca.gov, MMedina@sanbruno.ca.gov, lmason@sanbruno.ca.gov, mthurman@sanbruno.ca.gov**

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message: (Don't forget to replace the [x]'s with your information!)

To Mayor Medina, **Vice Mayor Salazar,**San Bruno City Council, **and elected and appointed officials**,

My name is **[YOUR NAME]** and I am a resident of San Bruno. As the nation grapples with the devastating, brutal deaths of George Floyd and Breonna Taylor (among so many others) and the economic impact of COVID-19, I am writing to express my strong concerns with the San Bruno Police Department budget.

**Accordingly, it has come to my attention that the meeting on 2nd Budget Hearing & Adoption for fiscal year (FY) 2020-21 is scheduled for June 23.** I am astonished to learn that the SBPD, **with a single police station**, received 38.**6**% of the **G**eneral **F**und **amended** budget in FY2019-20 and will receive **$19.3 million** (39.1%) in **the proposed** FY2020-21 **budget**, **more than the proposed budgets of Public Works, Community Development, and Community Services combined [1]**. **The SBPD budget is excessive for a small town, and I am alarmed to see that San Bruno’s forecasted financial plan projects an increase to almost $23 million in spending for FY 2024-25 on police despite historic unemployment, economic instability, and popular resistance to widespread police abuses.** This is even more astonishing considering the small, small numbers of officers who have graduated from a crisis training program: an estimated 9 in **20**19-20 and a target 6 in **20**20-21 **[1]**. I am deeply concerned about the priorities of the SBPD and San Bruno in general.

The **20**20-21 goal of expanding services to unhoused persons is certainly a noble one, but I am left wondering why such services are being rendered by police rather than trained counselors or experts in homelessness, substance use, and trauma. Similarly, I am alarmed by the extensive presence of officers in schools and concerned that youth-centered programming seems to be under the purview of the police department rather than the library or Recreation Services—or trained educators and counselors in general.

We must consider how far that 39.1% of the **General Fund** budget would go toward other non-violent, prevention-oriented services that address our livelihoods and humanity such as health services (include mental health services) social services, infrastructure, childcare assistance, homelessness services, libraries, and our parks and recreation services. Overall, we need to reimagine public safety to address root causes of community distress.

I call on you to **amend and** slash the FY 2020-21 SBPD budget and instead apply these resources towards these stated alternatives. I hope that our city does indeed have enough heart to make bold changes that uplift us all and establish a positive, nurturing foundation for generations to come.

Sincerely,
[YOUR NAME] 
[YOUR ADDRESS] 
[YOUR EMAIL] 
[YOUR PHONE NUMBER]

**Sources:
[1] CITY OF SAN BRUNO PROPOSED FY2020-21 OPERATING AND CAPITAL
BUDGET - https://www.sanbruno.ca.gov/civicax/filebank/blobdload.aspx?BlobID=31878**

--------------------------------

Verified the sources from San Bruno's [FY 2020-21 budget](https://www.sanbruno.ca.gov/civicax/filebank/blobdload.aspx?BlobID=31878). I combined a few elements of #1453 into this email, added the date for budget adoption (on page A3 of the FY 2020-21 budget), and made some clarifying edits as per the [email style guide](https://github.com/defund12/defund12.org/blob/master/EMAIL_TEMPLATE_STYLE_GUIDE.md). Marking this as ready for PR.

**Comment by root2point0** [comment] 2020-06-14 17:47
working on it

**Closed** 2020-06-15 11:38 UTC
Labels: ready-for-pr
