### ISSUE TITLE
ADD: Sunnyvale, CA

### ISSUE THREAD

**Issue by daswickerman** [defund12/defund12.org#692] opened 2020-06-07 19:34 UTC
To: kleincouncil@sunnyvale.ca.gov, smithcouncil@sunnyvale.ca.gov, larssoncouncil@sunnyvale.ca.gov, hendrickscouncil@sunnyvale.ca.gov,  MeltonCouncil@sunnyvale.ca.gov, goldmancouncil@sunnyvale.ca.gov, fongcouncil@sunnyvale.ca.gov
Subject: [*** INSERT UNIQUE SUBJECT LINE***]

Message (Don't forget to replace the [x]'s with your information!) 
Hello,

My name is [YOUR NAME] and I am a resident of Sunnyvale. I am writing to demand that funding is reallocated from Sunnyvale DPS to social and public programming that takes place in our communities. It is an outrage that 36% of city funding goes towards DPS while programs supporting the Library and community social programs receive only 7% of the city budget. 

We demand that the City Council defund Sunnyvale DPS. We join the calls of those across the country to defund the police. We demand a budget that adequately and effectively meets the needs of at-risk Sunnyvale residents during this trying and uncertain time, when livelihoods are on the line. We demand a budget that supports community wellbeing, rather than empowers police.

It is your duty to represent your constituents. I am urging you to completely revise the Sunnyvale city budget for 2020-2021 fiscal year. Public opinion is with me.

Thank you for your time,

[YOUR NAME] [YOUR ADDRESS] [YOUR EMAIL] [YOUR PHONE NUMBER]

**Comment by shortcircuit3** [comment] 2020-06-07 19:38
Duplicate of #691

**Closed by shortcircuit3** 2020-06-07 19:38 UTC
