### ISSUE TITLE
Request for Pawtucket, Rhode Island

### ISSUE THREAD

**Issue by asavino9** [defund12/defund12.org#696] opened 2020-06-07 19:39 UTC
Below are the email addresses for Governor Raimondo, Mayor Grebein, and the Pawtucket City Council members (who must approve the city budget):

Gina Raimondo - Governor: governor@governor.ri.gov 

Donald R. Grebein - Mayor: don@dongrebien.com 

Dylan M. Zelazo - Director of Administration: dzelazo@pawtucketri.com

Michael A. Araujo - Council at large: maraujo@pawtucketri.com

Albert J. Vitali, Jr. - Council at large: avitali@pawtucketri.com

Elena Vasquez - Council at large: evasquez@pawtucketri.com

David P. Moran - 1st District Councilor: pawtward1@gmail.com

Mark J. Wildenhain - 2nd District Councilor: MJWildenhain@pawtucketri.com

Terrence E. Mercer - 3rd District Councilor: tmercer@pawtucketri.com

John J. Barry, III - 4th District Councilor: No email listed but can be reached at (401) 723-3929

Meghan E. Kallman - 5th District Councilor: tmercer@pawtucketri.com

Timothy P. Rudd, Jr. - 6th District Counselor: trudd@pawtucketri.com 

COPY/PASTE EMAILS:

governor@governor.ri.gov, don@dongrebien.com, dzelazo@pawtucketri.com, maraujo@pawtucketri.com, avitali@pawtucketri.com, evasquez@pawtucketri.com, pawtward1@gmail.com, MJWildenhain@pawtucketri.com, tmercer@pawtucketri.com, tmercer@pawtucketri.com, trudd@pawtucketri.com 

SUBJECT: Defund Pawtucket Police

My name is [NAME] and I am a resident of Pawtucket. I am writing to demand that Governor Raimondo, Mayor Donald R. Grebien and the members of the City Council do everything in their power to adopt a budget that redirects all funds from the Pawtucket Police Department and towards community wellbeing, mental health and the needs of its residents.

It has become clear that police forces are ineffective at keeping local communities safe, and that they perpetuate the oppression of residents who are people of color, undocumented, mentally ill, disabled, and LGBTQ. In 2020, $26,299,326 was budgeted to the Police both uniform and civilian and with an increased approved budget of $29,086,990 for 2021.

We ask you consider how much those dollars could accomplish when used to fund low-income and public housing, education, resources for formerly incarcerated individuals, and public transportation. Comparatively only $593,607 on senior care and only ~$2million invested in libraries in 2020. We demand that excessive police force spending be allocated to programs that will ultimately protect and benefit the people of Pawtucket more than an overfunded police force.

Imagine what over $29 million could do for this community if it was invested in education, community mental health services, resources for formerly incarcerated, housing, and other services that have been proven to reduce crime and contribute to the safety and well-being of communities.

Pawtucket may be a small city in a small state, but we have shown that we can make a huge impact on America at large. We desperately need to change our financial priorities and let our tax dollars go to communities, not cops.

Thank you for your time.
[Name] [Address]
[Number]

**Comment by serifluous** [comment] 2020-06-08 00:19
Duplicate of issue #550

**Comment by bingbongle** [comment] 2020-06-08 12:36
Closing out, as it's a direct duplicate. Thanks for finding @serifluous !

**Closed by bingbongle** 2020-06-08 12:36 UTC
Labels: duplicate
